name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH access for deployment using the provided private key
      - name: Set up SSH for EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      # Step 3: Set up Git user identity for commits
      - name: Set Git user identity
        run: |
          git config --global user.name "abeantor"
          git config --global user.email "abuantor72@gmail.com"

      # Step 4: Push changes to GitHub (if any changes)
      - name: Push changes to GitHub
        run: |
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Deploy changes"
            git push origin main
          else
            echo "No changes to commit."
          fi

      # Step 5: Deploy and manage code on EC2
      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ubuntu@3.80.153.97 << 'EOF'
            # Change directory to the location where your DockerLab project is located
            cd ~/DockerLab/todo-list-app

            # Pull the latest changes from GitHub to the EC2 instance
            git pull origin main

            # Ensure Docker has permission for the current user
            sudo chmod 666 /var/run/docker.sock

            # Rebuild the Docker image with the latest changes
            sudo docker build -t todo-list-app .

            # Stop and remove the old container if it's running
            sudo docker stop todo-list-app || true
            sudo docker rm todo-list-app || true

            # Run the new container with updated code
            sudo docker run -d -p 80:3000 --name todo-list-app todo-list-app
          EOF
